config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :exhibitions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController

  def index
@exhibitions = [ 'picasso', 'renoir', 'klimt' ]
    if params[:exhibitions]
      @exhibitions = @exhibitions.select { |exhibition| exhibition.start_with?(params[:exhibition]) }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
    @members = ['thanh', 'dimitri', 'germain', 'damien', 'julien']
    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exhibitions/index.html.erb
<h1> Exhibitions </h1>
<ol>
<% @exhibitions.each do |exhibition|%>
<li><%= exhibition.capitalize%></li>
<%end%>
</ol>

<%= link_to 'home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> Our first view</h1>
<%= link_to 'home', root_path %>

app/views/pages/contact.html.erb
<ol>
<% @members.each do |member|%>
<li><%= member.capitalize %></li>
<%end%>
</ol>

<form action="/contact" method="get">
  <input type="text" name="member" value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<h1>Home</h1>
<h2>Now is <%=Time.now%></h2>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis eum cumque voluptas magnam exercitationem veritatis ad eaque iure, accusamus molestias assumenda facilis distinctio dicta necessitatibus architecto repudiandae animi sapiente pariatur.</p>
<%= link_to "Know more about us", about_path %>
<%= link_to "Meet our team", contact_path %>
<%= link_to "Exhibitions", exhibitions_path %>

app/views/users/user.html.erb
<h1>user Profile</h1>